language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t iamhi/udemy-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true iamhi/udemy-docker npm run test
