language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t iamhi/udemy-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true iamhi/udemy-docker npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "udemy-docker"
  env: "UdemyDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-066809830315"
  bucket_path: "udemy-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
