version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/react-client/node_modules
      - .:/usr/react-client
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/react-client/node_modules
      - .:/usr/react-client
    command: ["npm", "run", "test"]
